version: '3.9'

networks:
  books:

services:
  books-backend:
    build:
      context: ../..
      dockerfile: ./docker/development/Dockerfile
    ports:
      - "4000:4000"
    networks:
      - books
    volumes:
      - "../../:/app"
    working_dir: "/app"
